### ISSUE TITLE
Unless and until keywords.

### ISSUE THREAD

**Issue by gosukiwi** [gosukiwi/Blueberry#33]
I think `unless` and `until` are pretty cool. I'd like to add them to the language.

**Comment by TazeTSchnitzel** [comment]
They'd be `if !` and `while !` right?

**Comment by gosukiwi** [comment]
Yep.

**Comment by gosukiwi** [comment]
Addressed (in part) in 6d726a414fa3dac6bc2e5de0026402faa0c94781. Should really use branches instead if just dumping random commits :stuck_out_tongue:
