### ISSUE TITLE
Inline if and unless

### ISSUE THREAD

**Issue by gosukiwi** [gosukiwi/Blueberry#40]
Be able to make an if or unless statement in one line, a-la Coffeescript.

For example:

`a = 1 if some_expression()`
`b = 2 unless other_expression()`

**Comment by TazeTSchnitzel** [comment]
Like PHP:

    some_expression() and $a = 1;

**Comment by gosukiwi** [comment]
Addressed (in part) in 6d726a414fa3dac6bc2e5de0026402faa0c94781. Should really use branches instead if just dumping random commits :stuck_out_tongue:
